.TH OSHRUN 1 "OpenSHMEM Library Documentation"
.SH NAME
oshrun - Run a OpenSHMEM program
.SH DESCRIPTION
. --------->>>!!!!HEY DAVE WRITE THE DESCRIPTION HERE!!!!<<<-------
.SH COMMAND LINE ARGUMENTS
.TP 8
.B --help | -h
- Display this information

.SH NOTES
Options provided by mpirun can also be used by oshrun.

