.TH SHMEM_ATOMIC_AND 1 2017-06-06 "Intel Corp." "OpenSHEMEM Library Documentation"
.SH NAME
shmem_atomic_and \-   Atomically perform a non-fetching bitwise AND operation on a  remote data object.
.SH SYNOPSIS
.nf
.B C11: 
void shmem_atomic_and(TYPE *dest, TYPE value, int pe);
.B C/C++: 
void shmem_<TYPENAME>_atomic_and(TYPE *dest, TYPE value, int pe);

* TYPE is one of the extended AMO types
.fi
.SH DESCRIPTION
.SS Arguments
 
.BR "OUT " - 
.I dest
- A pointer to the remotely accessible data object to be updated.
 
.BR "IN " - 
.I value
- The operand to the bitwise AND operation.
 
.BR "IN " - 
.I pe
- An integer value for the 
PE
on which 
.I dest
is to be updated.
.SS API Description
 
.B shmem\_atomic\_and
atomically performs a non-fetching bitwise AND on the remotely accessible data object pointed to by 
.I dest
at PE  
.I pe
with the operand 
.IR "value" .
.SS Return Values
 None.
.SS API Notes
 None.
